# Generated by Django 5.1.11 on 2025-06-30 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discord_bot', '0002_add_integration_models'),
        ('teams', '0002_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='clubdiscordsettings',
            new_name='discord_bot_club_id_3490f1_idx',
            old_name='discord_cds_club_idx',
        ),
        migrations.RenameIndex(
            model_name='clubdiscordsettings',
            new_name='discord_bot_auto_cr_e291e5_idx',
            old_name='discord_cds_auto_create_channels_idx',
        ),
        migrations.RenameIndex(
            model_name='clubdiscordsettings',
            new_name='discord_bot_auto_sy_0e5f49_idx',
            old_name='discord_cds_auto_sync_members_idx',
        ),
        migrations.RenameIndex(
            model_name='discordmembersync',
            new_name='discord_bot_guild_i_a4a2a0_idx',
            old_name='discord_ms_guild_sync_timestamp_idx',
        ),
        migrations.RenameIndex(
            model_name='discordmembersync',
            new_name='discord_bot_sync_ty_c0ecd8_idx',
            old_name='discord_ms_sync_type_success_idx',
        ),
        migrations.RenameIndex(
            model_name='discordmembersync',
            new_name='discord_bot_success_ead0a1_idx',
            old_name='discord_ms_success_sync_timestamp_idx',
        ),
        migrations.RenameIndex(
            model_name='discordmembersync',
            new_name='discord_bot_trigger_4f05c3_idx',
            old_name='discord_ms_triggered_user_idx',
        ),
        migrations.RenameIndex(
            model_name='eventdiscordchannel',
            new_name='discord_bot_guild_i_faf916_idx',
            old_name='discord_ev_guild_status_idx',
        ),
        migrations.RenameIndex(
            model_name='eventdiscordchannel',
            new_name='discord_bot_text_ch_fe87e9_idx',
            old_name='discord_ev_text_channel_id_idx',
        ),
        migrations.RenameIndex(
            model_name='eventdiscordchannel',
            new_name='discord_bot_categor_c5bb50_idx',
            old_name='discord_ev_category_id_idx',
        ),
        migrations.RenameIndex(
            model_name='eventdiscordchannel',
            new_name='discord_bot_event_s_7b8c1a_idx',
            old_name='discord_ev_event_signup_sheet_idx',
        ),
        migrations.RenameIndex(
            model_name='eventdiscordchannel',
            new_name='discord_bot_status_050c21_idx',
            old_name='discord_ev_status_created_at_idx',
        ),
        migrations.RenameIndex(
            model_name='eventdiscordchannel',
            new_name='discord_bot_auto_ar_a1c177_idx',
            old_name='discord_ev_auto_archive_status_idx',
        ),
        migrations.AddField(
            model_name='discordguild',
            name='bot_permissions',
            field=models.BigIntegerField(default=0, help_text='Bot permissions as integer bitfield'),
        ),
        migrations.AddField(
            model_name='discordguild',
            name='icon_url',
            field=models.URLField(blank=True, help_text='Guild icon URL'),
        ),
        migrations.AddField(
            model_name='discordguild',
            name='last_sync_timestamp',
            field=models.DateTimeField(blank=True, help_text='Last time member sync was performed', null=True),
        ),
        migrations.AddField(
            model_name='discordguild',
            name='member_count',
            field=models.IntegerField(default=0, help_text='Total number of members in the Discord guild'),
        ),
        migrations.AddField(
            model_name='discordguild',
            name='owner_id',
            field=models.CharField(blank=True, help_text='Discord guild owner ID', max_length=50),
        ),
        migrations.AddField(
            model_name='discordguild',
            name='region',
            field=models.CharField(blank=True, help_text='Guild voice region', max_length=50),
        ),
        migrations.AddField(
            model_name='discordguild',
            name='verification_level',
            field=models.IntegerField(default=0, help_text='Guild verification level (0-4)'),
        ),
        migrations.AlterField(
            model_name='discordmembersync',
            name='guild',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_syncs', to='discord_bot.discordguild'),
        ),
        migrations.AlterField(
            model_name='eventdiscordchannel',
            name='event_signup_sheet',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discord_channel', to='teams.clubeventsignupsheet'),
        ),
        migrations.AlterField(
            model_name='eventdiscordchannel',
            name='guild',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_channels', to='discord_bot.discordguild'),
        ),
        migrations.AddIndex(
            model_name='discordguild',
            index=models.Index(fields=['guild_id'], name='discord_bot_guild_i_d3f0e4_idx'),
        ),
        migrations.AddIndex(
            model_name='discordguild',
            index=models.Index(fields=['club', 'is_active'], name='discord_bot_club_id_0e8249_idx'),
        ),
        migrations.AddIndex(
            model_name='discordguild',
            index=models.Index(fields=['last_sync_timestamp'], name='discord_bot_last_sy_81e447_idx'),
        ),
    ]
