# Generated by Django 5.1.11 on 2025-07-01 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discord_bot', '0003_rename_discord_cds_club_idx_discord_bot_club_id_3490f1_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubdiscordsettings',
            name='enable_join_request_notifications',
            field=models.BooleanField(default=True, help_text='Send notifications when users request to join'),
        ),
        migrations.AddField(
            model_name='clubdiscordsettings',
            name='join_requests_channel_id',
            field=models.CharField(blank=True, help_text='Discord channel ID for member join requests', max_length=50),
        ),
    ]
