# Generated by Django 5.1.11 on 2025-06-28 16:04

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('subject', models.CharField(choices=[('general', 'General Inquiry'), ('support', 'Technical Support'), ('feature', 'Feature Request'), ('bug', 'Bug Report'), ('account', 'Account Issues'), ('privacy', 'Privacy Concerns'), ('business', 'Business Inquiry'), ('other', 'Other')], max_length=20, verbose_name='Subject')),
                ('platform', models.CharField(blank=True, choices=[('', 'Not specified'), ('iracing', 'iRacing'), ('acc', 'Assetto Corsa Competizione'), ('rf2', 'rFactor 2'), ('other', 'Other'), ('none', 'Not applicable')], max_length=20, verbose_name='Racing Platform')),
                ('message', models.TextField(verbose_name='Message')),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes for staff')),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MediaGallery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.CharField(max_length=255)),
                ('gallery_type', models.CharField(choices=[('screenshots', 'Screenshots'), ('photos', 'Photos'), ('logos', 'Logos'), ('promotional', 'Promotional Images'), ('technical', 'Technical Diagrams'), ('liveries', 'Car Liveries'), ('track_maps', 'Track SVG Maps'), ('other', 'Other')], default='photos', help_text='Type of gallery/images', max_length=20)),
                ('image', models.ImageField(help_text='Gallery image file', upload_to='gallery/%Y/%m/')),
                ('caption', models.CharField(blank=True, help_text='Optional image caption', max_length=255)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('original_filename', models.CharField(blank=True, help_text='Original filename from external source', max_length=255)),
                ('original_url', models.URLField(blank=True, help_text='Original URL where image was downloaded from')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Media Gallery Item',
                'verbose_name_plural': 'Media Gallery Items',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
