# Generated by Django 5.1.11 on 2025-06-28 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User who submitted this message (if authenticated)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mediagallery',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddIndex(
            model_name='mediagallery',
            index=models.Index(fields=['content_type', 'object_id', 'order'], name='core_mediag_content_e6a1b4_idx'),
        ),
        migrations.AddIndex(
            model_name='mediagallery',
            index=models.Index(fields=['content_type', 'object_id'], name='core_mediag_content_1834df_idx'),
        ),
        migrations.AddIndex(
            model_name='mediagallery',
            index=models.Index(fields=['gallery_type'], name='core_mediag_gallery_93e36f_idx'),
        ),
    ]
