# Generated by Django 5.1.11 on 2025-06-26 00:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0002_create_base_seed_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaGallery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.CharField(max_length=255)),
                ('gallery_type', models.CharField(choices=[('screenshots', 'Screenshots'), ('photos', 'Photos'), ('logos', 'Logos'), ('promotional', 'Promotional Images'), ('technical', 'Technical Diagrams'), ('liveries', 'Car Liveries'), ('other', 'Other')], default='photos', help_text='Type of gallery/images', max_length=20)),
                ('image', models.ImageField(help_text='Gallery image file', upload_to='gallery/%Y/%m/')),
                ('caption', models.CharField(blank=True, help_text='Optional image caption', max_length=255)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('original_filename', models.CharField(blank=True, help_text='Original filename from external source', max_length=255)),
                ('original_url', models.URLField(blank=True, help_text='Original URL where image was downloaded from')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Media Gallery Item',
                'verbose_name_plural': 'Media Gallery Items',
                'ordering': ['order', 'created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id', 'order'], name='core_mediag_content_e6a1b4_idx'), models.Index(fields=['content_type', 'object_id'], name='core_mediag_content_1834df_idx'), models.Index(fields=['gallery_type'], name='core_mediag_gallery_93e36f_idx')],
            },
        ),
    ]
