# Generated by Django 5.1.11 on 2025-06-26 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_media_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediagallery',
            name='gallery_type',
            field=models.CharField(choices=[('screenshots', 'Screenshots'), ('photos', 'Photos'), ('logos', 'Logos'), ('promotional', 'Promotional Images'), ('technical', 'Technical Diagrams'), ('liveries', 'Car Liveries'), ('track_maps', 'Track SVG Maps'), ('other', 'Other')], default='photos', help_text='Type of gallery/images', max_length=20),
        ),
    ]
