# Generated by Django 5.1.11 on 2025-06-20 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubmember',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('teams_manager', 'Teams Manager'), ('member', 'Member')], default='member', max_length=50),
        ),
    ]
