# Generated by Django 5.1.11 on 2025-07-01 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='banner_image',
            field=models.ImageField(blank=True, help_text='Banner image for the club', null=True, upload_to='club_banners/'),
        ),
    ]
