# Generated by Django 5.1.11 on 2025-07-01 11:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_club_banner_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubJoinRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(help_text="User's explanation for wanting to join the club", max_length=1000)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('admin_response', models.TextField(blank=True, help_text="Admin's message when approving/rejecting the request", max_length=500)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('discord_message_id', models.CharField(blank=True, help_text='Discord message ID for the join request notification', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='clubinvitation',
            name='teams_clubi_club_id_98c7cf_idx',
        ),
        migrations.AddIndex(
            model_name='clubinvitation',
            index=models.Index(fields=['club'], name='teams_clubi_club_id_356b91_idx'),
        ),
        migrations.AddField(
            model_name='clubjoinrequest',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='teams.club'),
        ),
        migrations.AddField(
            model_name='clubjoinrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, help_text='Admin who reviewed this request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_join_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clubjoinrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_join_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='clubjoinrequest',
            index=models.Index(fields=['club', 'status'], name='teams_clubj_club_id_c46be2_idx'),
        ),
        migrations.AddIndex(
            model_name='clubjoinrequest',
            index=models.Index(fields=['user'], name='teams_clubj_user_id_bef22e_idx'),
        ),
        migrations.AddIndex(
            model_name='clubjoinrequest',
            index=models.Index(fields=['status'], name='teams_clubj_status_a687d9_idx'),
        ),
        migrations.AddIndex(
            model_name='clubjoinrequest',
            index=models.Index(fields=['created_at'], name='teams_clubj_created_b5b39c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='clubjoinrequest',
            unique_together={('club', 'user')},
        ),
    ]
