# Generated by Django 5.1.11 on 2025-06-26 19:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sim', '0019_remove_simprofile_sim_simprof_simulat_77d43c_idx_and_more'),
        ('teams', '0006_remove_evententry_event_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='team',
            name='teams_team_externa_6b6a68_idx',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='external_team_id',
            new_name='sim_api_id',
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['sim_api_id', 'source_simulator'], name='teams_team_sim_api_d3aaaf_idx'),
        ),
    ]
