# Generated by Django 5.1.11 on 2025-06-26 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0007_remove_team_teams_team_externa_6b6a68_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='logo_url',
        ),
        migrations.RemoveField(
            model_name='club',
            name='social_links',
        ),
        migrations.AddField(
            model_name='club',
            name='discord_url',
            field=models.URLField(blank=True, help_text='Discord server invite link'),
        ),
        migrations.AddField(
            model_name='club',
            name='facebook_url',
            field=models.URLField(blank=True, help_text='Facebook page URL'),
        ),
        migrations.AddField(
            model_name='club',
            name='instagram_url',
            field=models.URLField(blank=True, help_text='Instagram profile URL'),
        ),
        migrations.AddField(
            model_name='club',
            name='logo',
            field=models.ImageField(blank=True, help_text='Club logo image', null=True, upload_to='club_logos/'),
        ),
        migrations.AddField(
            model_name='club',
            name='twitch_url',
            field=models.URLField(blank=True, help_text='Twitch channel URL'),
        ),
        migrations.AddField(
            model_name='club',
            name='twitter_url',
            field=models.URLField(blank=True, help_text='Twitter/X profile URL'),
        ),
        migrations.AddField(
            model_name='club',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='YouTube channel URL'),
        ),
    ]
