# Generated by Django 5.1.11 on 2025-01-26 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0008_update_club_model_fields'),
        ('sim', '0007_add_unified_participation_models'),
    ]

    operations = [
        # ClubEvent model has been removed from models.py
        # This migration is mainly to mark the removal in the database
        # No actual database operations needed since model was already removed
    ]
