# Generated by Django 5.1.2

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0009_remove_club_event_model'),
        ('sim', '0008_alter_event_event_source'),  # Assuming this is the latest sim migration
    ]

    operations = [
        # Add signup_context_club field
        migrations.AddField(
            model_name='eventparticipation',
            name='signup_context_club',
            field=models.ForeignKey(
                blank=True,
                help_text='Which club this signup is associated with (for club-organized signups)',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='event_signups',
                to='teams.club'
            ),
        ),
        
        # Add preferred_instances many-to-many field
        migrations.AddField(
            model_name='eventparticipation',
            name='preferred_instances',
            field=models.ManyToManyField(
                blank=True,
                related_name='preferred_participations',
                to='sim.eventinstance'
            ),
        ),
        
        # Add assigned_instance field
        migrations.AddField(
            model_name='eventparticipation',
            name='assigned_instance',
            field=models.ForeignKey(
                blank=True,
                help_text='Final instance assignment after team formation',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='assigned_participations',
                to='sim.eventinstance'
            ),
        ),
        
        # Remove old unique_together constraints
        migrations.AlterUniqueTogether(
            name='eventparticipation',
            unique_together=set(),
        ),
        
        # Add new unique constraints at instance level
        migrations.AddConstraint(
            model_name='eventparticipation',
            constraint=models.UniqueConstraint(
                condition=models.Q(('assigned_instance__isnull', False), ('user__isnull', False)),
                fields=['assigned_instance', 'user'],
                name='unique_user_event_instance_participation'
            ),
        ),
        migrations.AddConstraint(
            model_name='eventparticipation',
            constraint=models.UniqueConstraint(
                condition=models.Q(('assigned_instance__isnull', False), ('team__isnull', False)),
                fields=['assigned_instance', 'team'],
                name='unique_team_event_instance_participation'
            ),
        ),
        
        # Add new indexes
        migrations.AddIndex(
            model_name='eventparticipation',
            index=models.Index(fields=['signup_context_club', 'event'], name='teams_event_signup__b8c4d9_idx'),
        ),
        migrations.AddIndex(
            model_name='eventparticipation',
            index=models.Index(fields=['assigned_instance', 'status'], name='teams_event_assigne_f8a2c1_idx'),
        ),
    ] 