# Generated by Django 5.1.2

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teams', '0010_add_club_context_and_instance_constraints'),
        ('sim', '0008_alter_event_event_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubEventSignupSheet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text="Club-specific title for this signup (e.g., 'Team Endurance - Le Mans')", max_length=255)),
                ('description', models.TextField(blank=True, help_text='Club-specific instructions or notes about this event')),
                ('signup_opens', models.DateTimeField(help_text='When signups open for club members')),
                ('signup_closes', models.DateTimeField(help_text='When signups close')),
                ('max_teams', models.IntegerField(blank=True, help_text='Maximum number of teams the club will enter', null=True)),
                ('target_team_size', models.IntegerField(default=4, help_text='Target number of drivers per team')),
                ('min_drivers_per_team', models.IntegerField(default=2, help_text='Minimum drivers needed to form a team')),
                ('max_drivers_per_team', models.IntegerField(default=6, help_text='Maximum drivers allowed per team')),
                ('min_license_level', models.CharField(blank=True, help_text='Minimum license level required (club-specific requirement)', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open for Signups'), ('closed', 'Signups Closed'), ('teams_forming', 'Teams Being Formed'), ('teams_finalized', 'Teams Finalized'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('notes_for_admins', models.TextField(blank=True, help_text='Internal notes for club admins/managers')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_signup_sheets', to='teams.club')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_signup_sheets', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_signup_sheets', to='sim.event')),
            ],
            options={
                'indexes': [
                    models.Index(fields=['club', 'status'], name='teams_clube_club_id_4a0b12_idx'),
                    models.Index(fields=['event', 'status'], name='teams_clube_event_i_3c8d45_idx'),
                    models.Index(fields=['signup_opens', 'signup_closes'], name='teams_clube_signup__7f2a91_idx'),
                    models.Index(fields=['status'], name='teams_clube_status_9b3c22_idx'),
                ],
            },
        ),
        migrations.AlterUniqueTogether(
            name='clubeventsignupsheet',
            unique_together={('club', 'event')},
        ),
    ] 