# Generated by Django 5.1.11 on 2025-06-27 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0011_add_club_event_signup_sheet'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='clubevent',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='clubevent',
            name='base_event',
        ),
        migrations.RemoveField(
            model_name='clubevent',
            name='club',
        ),
        migrations.RemoveField(
            model_name='clubevent',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='eventparticipation',
            name='club_event',
        ),
        migrations.RemoveIndex(
            model_name='eventparticipation',
            name='teams_event_club_ev_762335_idx',
        ),
        migrations.RenameIndex(
            model_name='clubeventsignupsheet',
            new_name='teams_clube_club_id_213dee_idx',
            old_name='teams_clube_club_id_4a0b12_idx',
        ),
        migrations.RenameIndex(
            model_name='clubeventsignupsheet',
            new_name='teams_clube_event_i_90f8f1_idx',
            old_name='teams_clube_event_i_3c8d45_idx',
        ),
        migrations.RenameIndex(
            model_name='clubeventsignupsheet',
            new_name='teams_clube_signup__94e2d5_idx',
            old_name='teams_clube_signup__7f2a91_idx',
        ),
        migrations.RenameIndex(
            model_name='clubeventsignupsheet',
            new_name='teams_clube_status_69362a_idx',
            old_name='teams_clube_status_9b3c22_idx',
        ),
        migrations.RenameIndex(
            model_name='eventparticipation',
            new_name='teams_event_signup__d95781_idx',
            old_name='teams_event_signup__b8c4d9_idx',
        ),
        migrations.RenameIndex(
            model_name='eventparticipation',
            new_name='teams_event_assigne_8df1c6_idx',
            old_name='teams_event_assigne_f8a2c1_idx',
        ),
        migrations.DeleteModel(
            name='ClubEvent',
        ),
    ]
