# Generated by Django 5.1.11 on 2025-06-18 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sim', '0001_initial'),
    ]

    operations = [
    ]
