# Generated by Django 5.1.11 on 2025-06-28 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sim', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='organizing_club',
            field=models.ForeignKey(blank=True, help_text='Club organizing this event (if club-organized)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organized_events', to='teams.club'),
        ),
    ]
