# Generated by Django 5.1.11 on 2025-06-28 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sim', '0002_initial'),
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='organizing_user',
            field=models.ForeignKey(blank=True, help_text='User organizing this event (if user-created)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organized_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='carrestriction',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_restrictions', to='sim.event'),
        ),
        migrations.AddField(
            model_name='eventclass',
            name='car_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_classes', to='sim.carclass'),
        ),
        migrations.AddField(
            model_name='eventclass',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='sim.event'),
        ),
        migrations.AddField(
            model_name='eventsession',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='sim.event'),
        ),
        migrations.AddField(
            model_name='participantresult',
            name='event_result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='sim.eventresult'),
        ),
        migrations.AddField(
            model_name='profilerating',
            name='rating_system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_ratings', to='sim.ratingsystem'),
        ),
        migrations.AddField(
            model_name='season',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='sim.series'),
        ),
        migrations.AddField(
            model_name='event',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='sim.series'),
        ),
        migrations.AddField(
            model_name='simcar',
            name='car_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sim_cars', to='sim.carmodel'),
        ),
        migrations.AddField(
            model_name='simcar',
            name='pit_data',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sim_car', to='sim.pitdata'),
        ),
        migrations.AddField(
            model_name='carrestriction',
            name='sim_car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_restrictions', to='sim.simcar'),
        ),
        migrations.AddField(
            model_name='simlayout',
            name='pit_data',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sim_layout', to='sim.pitdata'),
        ),
        migrations.AddField(
            model_name='laptime',
            name='sim_layout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lap_times', to='sim.simlayout'),
        ),
        migrations.AddField(
            model_name='event',
            name='sim_layout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='sim.simlayout'),
        ),
        migrations.AddField(
            model_name='simprofile',
            name='linked_user',
            field=models.ForeignKey(blank=True, help_text='User who has claimed this profile', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_sim_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profilerating',
            name='sim_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='sim.simprofile'),
        ),
        migrations.AddField(
            model_name='participantresult',
            name='sim_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='race_results', to='sim.simprofile'),
        ),
        migrations.AddField(
            model_name='laptime',
            name='sim_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lap_times', to='sim.simprofile'),
        ),
        migrations.AddField(
            model_name='simprofilecarownership',
            name='sim_car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='sim.simcar'),
        ),
        migrations.AddField(
            model_name='simprofilecarownership',
            name='sim_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_cars', to='sim.simprofile'),
        ),
        migrations.AddField(
            model_name='simprofiletrackownership',
            name='sim_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_tracks', to='sim.simprofile'),
        ),
        migrations.AddField(
            model_name='simprofiletrackownership',
            name='sim_track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='sim.simtrack'),
        ),
        migrations.AddField(
            model_name='simlayout',
            name='sim_track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layouts', to='sim.simtrack'),
        ),
        migrations.AddField(
            model_name='simtrack',
            name='simulator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sim_tracks', to='sim.simulator'),
        ),
        migrations.AddField(
            model_name='simprofile',
            name='simulator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sim_profiles', to='sim.simulator'),
        ),
        migrations.AddField(
            model_name='simcar',
            name='simulator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sim_cars', to='sim.simulator'),
        ),
        migrations.AddField(
            model_name='series',
            name='simulator',
            field=models.ForeignKey(blank=True, help_text='Simulator this series belongs to (if simulator-specific)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='series', to='sim.simulator'),
        ),
        migrations.AddField(
            model_name='ratingsystem',
            name='simulator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_systems', to='sim.simulator'),
        ),
        migrations.AddField(
            model_name='event',
            name='simulator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='sim.simulator'),
        ),
        migrations.AddField(
            model_name='carclass',
            name='simulator',
            field=models.ForeignKey(blank=True, help_text='Simulator this car class belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car_classes', to='sim.simulator'),
        ),
        migrations.AddField(
            model_name='teamresult',
            name='event_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_results', to='sim.eventresult'),
        ),
        migrations.AddField(
            model_name='teamresult',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='race_results', to='teams.team'),
        ),
        migrations.AddField(
            model_name='participantresult',
            name='team_result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='sim.teamresult'),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='sim.event'),
        ),
        migrations.AddField(
            model_name='eventresult',
            name='time_slot',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='sim.timeslot'),
        ),
        migrations.AddIndex(
            model_name='trackmodel',
            index=models.Index(fields=['slug'], name='sim_trackmo_slug_f4115e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='trackmodel',
            unique_together={('name', 'country', 'slug')},
        ),
        migrations.AddField(
            model_name='simtrack',
            name='track_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sim_tracks', to='sim.trackmodel'),
        ),
        migrations.AddField(
            model_name='weatherforecast',
            name='time_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_forecasts', to='sim.timeslot'),
        ),
        migrations.AddIndex(
            model_name='eventclass',
            index=models.Index(fields=['event'], name='sim_eventcl_event_i_0e888a_idx'),
        ),
        migrations.AddIndex(
            model_name='eventclass',
            index=models.Index(fields=['car_class'], name='sim_eventcl_car_cla_f2bcb5_idx'),
        ),
        migrations.AddIndex(
            model_name='eventclass',
            index=models.Index(fields=['class_order'], name='sim_eventcl_class_o_9e2123_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='eventclass',
            unique_together={('event', 'slug')},
        ),
        migrations.AddIndex(
            model_name='eventsession',
            index=models.Index(fields=['event'], name='sim_eventse_event_i_a9b1c3_idx'),
        ),
        migrations.AddIndex(
            model_name='eventsession',
            index=models.Index(fields=['session_type'], name='sim_eventse_session_0e9a67_idx'),
        ),
        migrations.AddIndex(
            model_name='season',
            index=models.Index(fields=['series'], name='sim_season_series__9489da_idx'),
        ),
        migrations.AddIndex(
            model_name='season',
            index=models.Index(fields=['external_season_id'], name='sim_season_externa_b2f808_idx'),
        ),
        migrations.AddIndex(
            model_name='season',
            index=models.Index(fields=['active'], name='sim_season_active_5c76c4_idx'),
        ),
        migrations.AddIndex(
            model_name='season',
            index=models.Index(fields=['start_date', 'end_date'], name='sim_season_start_d_6302da_idx'),
        ),
        migrations.AddIndex(
            model_name='season',
            index=models.Index(fields=['slug'], name='sim_season_slug_7f875a_idx'),
        ),
        migrations.AddIndex(
            model_name='carrestriction',
            index=models.Index(fields=['event'], name='sim_carrest_event_i_01d6f2_idx'),
        ),
        migrations.AddIndex(
            model_name='carrestriction',
            index=models.Index(fields=['sim_car'], name='sim_carrest_sim_car_5d1c2e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='carrestriction',
            unique_together={('event', 'sim_car')},
        ),
        migrations.AddIndex(
            model_name='profilerating',
            index=models.Index(fields=['sim_profile', 'rating_system', 'discipline', 'recorded_at'], name='sim_profile_sim_pro_098557_idx'),
        ),
        migrations.AddIndex(
            model_name='laptime',
            index=models.Index(fields=['sim_profile'], name='sim_laptime_sim_pro_6e2f40_idx'),
        ),
        migrations.AddIndex(
            model_name='laptime',
            index=models.Index(fields=['sim_layout'], name='sim_laptime_sim_lay_e90898_idx'),
        ),
        migrations.AddIndex(
            model_name='laptime',
            index=models.Index(fields=['recorded_at'], name='sim_laptime_recorde_e32a98_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='simprofilecarownership',
            unique_together={('sim_profile', 'sim_car')},
        ),
        migrations.AlterUniqueTogether(
            name='simprofiletrackownership',
            unique_together={('sim_profile', 'sim_track')},
        ),
        migrations.AddIndex(
            model_name='simlayout',
            index=models.Index(fields=['sim_track'], name='sim_simlayo_sim_tra_7a0dd1_idx'),
        ),
        migrations.AddIndex(
            model_name='simlayout',
            index=models.Index(fields=['sim_track', 'slug'], name='sim_simlayo_sim_tra_c63ed2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='simlayout',
            unique_together={('sim_track', 'layout_code', 'slug')},
        ),
        migrations.AddIndex(
            model_name='simprofile',
            index=models.Index(fields=['simulator', 'sim_api_id'], name='sim_simprof_simulat_07fd75_idx'),
        ),
        migrations.AddIndex(
            model_name='simprofile',
            index=models.Index(fields=['linked_user'], name='sim_simprof_linked__c56419_idx'),
        ),
        migrations.AddIndex(
            model_name='simprofile',
            index=models.Index(fields=['is_public'], name='sim_simprof_is_publ_2961b9_idx'),
        ),
        migrations.AddIndex(
            model_name='simprofile',
            index=models.Index(fields=['profile_name'], name='sim_simprof_profile_b205fa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='simprofile',
            unique_together={('simulator', 'sim_api_id')},
        ),
        migrations.AddIndex(
            model_name='simcar',
            index=models.Index(fields=['car_model'], name='sim_simcar_car_mod_994d87_idx'),
        ),
        migrations.AddIndex(
            model_name='simcar',
            index=models.Index(fields=['simulator', 'sim_api_id'], name='sim_simcar_simulat_3f508c_idx'),
        ),
        migrations.AddIndex(
            model_name='simcar',
            index=models.Index(fields=['simulator', 'package_id'], name='sim_simcar_simulat_6b6231_idx'),
        ),
        migrations.AddIndex(
            model_name='simcar',
            index=models.Index(fields=['package_id'], name='sim_simcar_package_657439_idx'),
        ),
        migrations.AddIndex(
            model_name='simcar',
            index=models.Index(fields=['is_active'], name='sim_simcar_is_acti_e8cada_idx'),
        ),
        migrations.AddIndex(
            model_name='simcar',
            index=models.Index(fields=['free_with_subscription'], name='sim_simcar_free_wi_53c096_idx'),
        ),
        migrations.AddIndex(
            model_name='simcar',
            index=models.Index(fields=['is_purchasable'], name='sim_simcar_is_purc_14387c_idx'),
        ),
        migrations.AddIndex(
            model_name='simcar',
            index=models.Index(fields=['price'], name='sim_simcar_price_3b6622_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='simcar',
            unique_together={('simulator', 'sim_api_id')},
        ),
        migrations.AddIndex(
            model_name='series',
            index=models.Index(fields=['slug'], name='sim_series_slug_3d94f6_idx'),
        ),
        migrations.AddIndex(
            model_name='series',
            index=models.Index(fields=['external_series_id'], name='sim_series_externa_936a6b_idx'),
        ),
        migrations.AddIndex(
            model_name='series',
            index=models.Index(fields=['simulator'], name='sim_series_simulat_53c06f_idx'),
        ),
        migrations.AddIndex(
            model_name='series',
            index=models.Index(fields=['category'], name='sim_series_categor_bf71d5_idx'),
        ),
        migrations.AddIndex(
            model_name='series',
            index=models.Index(fields=['is_official'], name='sim_series_is_offi_0a6511_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ratingsystem',
            unique_together={('simulator', 'code')},
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['series'], name='sim_event_series__e9b407_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['simulator'], name='sim_event_simulat_82ed9a_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['sim_layout'], name='sim_event_sim_lay_21fc33_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['event_date'], name='sim_event_event_d_64c9d1_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['status'], name='sim_event_status_cb577d_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['slug'], name='sim_event_slug_5d6224_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['event_source'], name='sim_event_event_s_2e349b_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['organizing_club'], name='sim_event_organiz_4b1466_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['organizing_user'], name='sim_event_organiz_3f6cb7_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['visibility'], name='sim_event_visibil_bfa3cd_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['event_source', 'visibility'], name='sim_event_event_s_c47d84_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['round_number'], name='sim_event_round_n_baf491_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['start_date', 'end_date'], name='sim_event_start_d_0b0c4b_idx'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('organizing_club__isnull', False), ('organizing_user__isnull', True)), models.Q(('organizing_club__isnull', True), ('organizing_user__isnull', False)), models.Q(('organizing_club__isnull', True), ('organizing_user__isnull', True)), _connector='OR'), name='event_has_single_organizer_or_none'),
        ),
        migrations.AddIndex(
            model_name='carclass',
            index=models.Index(fields=['simulator'], name='sim_carclas_simulat_571f2e_idx'),
        ),
        migrations.AddIndex(
            model_name='carclass',
            index=models.Index(fields=['sim_api_id'], name='sim_carclas_sim_api_7fb0ee_idx'),
        ),
        migrations.AddIndex(
            model_name='carclass',
            index=models.Index(fields=['name'], name='sim_carclas_name_fa176e_idx'),
        ),
        migrations.AddIndex(
            model_name='carclass',
            index=models.Index(fields=['slug'], name='sim_carclas_slug_eb2e71_idx'),
        ),
        migrations.AddConstraint(
            model_name='carclass',
            constraint=models.UniqueConstraint(condition=models.Q(('sim_api_id__isnull', False), ('simulator__isnull', False)), fields=('simulator', 'sim_api_id'), name='unique_simulator_sim_api_id'),
        ),
        migrations.AddIndex(
            model_name='teamresult',
            index=models.Index(fields=['event_result', 'finish_position'], name='sim_teamres_event_r_100659_idx'),
        ),
        migrations.AddIndex(
            model_name='teamresult',
            index=models.Index(fields=['team', 'finish_position'], name='sim_teamres_team_id_6b8d2d_idx'),
        ),
        migrations.AddIndex(
            model_name='teamresult',
            index=models.Index(fields=['car_class_id', 'finish_position_in_class'], name='sim_teamres_car_cla_442091_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='teamresult',
            unique_together={('event_result', 'team')},
        ),
        migrations.AddIndex(
            model_name='participantresult',
            index=models.Index(fields=['event_result', 'finish_position'], name='sim_partici_event_r_fa0c6a_idx'),
        ),
        migrations.AddIndex(
            model_name='participantresult',
            index=models.Index(fields=['team_result', 'finish_position'], name='sim_partici_team_re_55b2c7_idx'),
        ),
        migrations.AddIndex(
            model_name='participantresult',
            index=models.Index(fields=['sim_profile', 'finish_position'], name='sim_partici_sim_pro_6362b8_idx'),
        ),
        migrations.AddIndex(
            model_name='participantresult',
            index=models.Index(fields=['oldi_rating', 'newi_rating'], name='sim_partici_oldi_ra_867221_idx'),
        ),
        migrations.AddIndex(
            model_name='participantresult',
            index=models.Index(fields=['car_class_id', 'finish_position_in_class'], name='sim_partici_car_cla_938500_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='participantresult',
            unique_together={('event_result', 'sim_profile'), ('team_result', 'sim_profile')},
        ),
        migrations.AddIndex(
            model_name='timeslot',
            index=models.Index(fields=['event'], name='sim_timeslo_event_i_b7a807_idx'),
        ),
        migrations.AddIndex(
            model_name='timeslot',
            index=models.Index(fields=['start_time'], name='sim_timeslo_start_t_9a382a_idx'),
        ),
        migrations.AddIndex(
            model_name='timeslot',
            index=models.Index(fields=['registration_open'], name='sim_timeslo_registr_0f103d_idx'),
        ),
        migrations.AddIndex(
            model_name='timeslot',
            index=models.Index(fields=['registration_ends'], name='sim_timeslo_registr_511490_idx'),
        ),
        migrations.AddIndex(
            model_name='timeslot',
            index=models.Index(fields=['event', 'slug'], name='sim_timeslo_event_i_fefcdf_idx'),
        ),
        migrations.AddIndex(
            model_name='timeslot',
            index=models.Index(fields=['external_subsession_id'], name='sim_timeslo_externa_a28805_idx'),
        ),
        migrations.AddIndex(
            model_name='timeslot',
            index=models.Index(fields=['external_session_id'], name='sim_timeslo_externa_c4a5d4_idx'),
        ),
        migrations.AddIndex(
            model_name='timeslot',
            index=models.Index(fields=['is_predicted', 'is_matched'], name='sim_timeslo_is_pred_a8023a_idx'),
        ),
        migrations.AddIndex(
            model_name='timeslot',
            index=models.Index(fields=['start_time', 'event'], name='sim_timeslo_start_t_7b655b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together={('event', 'slug')},
        ),
        migrations.AddIndex(
            model_name='eventresult',
            index=models.Index(fields=['subsession_id'], name='sim_eventre_subsess_fff5f4_idx'),
        ),
        migrations.AddIndex(
            model_name='eventresult',
            index=models.Index(fields=['time_slot'], name='sim_eventre_time_sl_0fe3c9_idx'),
        ),
        migrations.AddIndex(
            model_name='eventresult',
            index=models.Index(fields=['start_time'], name='sim_eventre_start_t_cd4b77_idx'),
        ),
        migrations.AddIndex(
            model_name='eventresult',
            index=models.Index(fields=['is_processed'], name='sim_eventre_is_proc_5a118c_idx'),
        ),
        migrations.AddIndex(
            model_name='simtrack',
            index=models.Index(fields=['simulator'], name='sim_simtrac_simulat_5dec09_idx'),
        ),
        migrations.AddIndex(
            model_name='simtrack',
            index=models.Index(fields=['track_model'], name='sim_simtrac_track_m_e85dad_idx'),
        ),
        migrations.AddIndex(
            model_name='simtrack',
            index=models.Index(fields=['simulator', 'slug'], name='sim_simtrac_simulat_133955_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='simtrack',
            unique_together={('simulator', 'sim_api_id'), ('simulator', 'slug'), ('simulator', 'track_model')},
        ),
        migrations.AddIndex(
            model_name='weatherforecast',
            index=models.Index(fields=['time_slot'], name='sim_weather_time_sl_ec829e_idx'),
        ),
        migrations.AddIndex(
            model_name='weatherforecast',
            index=models.Index(fields=['time_offset'], name='sim_weather_time_of_2965e8_idx'),
        ),
        migrations.AddIndex(
            model_name='weatherforecast',
            index=models.Index(fields=['timestamp'], name='sim_weather_timesta_b106c5_idx'),
        ),
    ]
