# Generated by Django 5.1.11 on 2025-06-19 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sim', '0002_remove_simulator_version'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='simulator',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='simulator',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='simulators/icons/'),
        ),
        migrations.AddField(
            model_name='simulator',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='simulators/logos/'),
        ),
        migrations.AlterField(
            model_name='simulator',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.RemoveField(
            model_name='simulator',
            name='version',
        ),
    ]
