# Generated by Django 5.1.11 on 2025-06-28 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sim', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='season',
            name='current_race_week',
        ),
        migrations.RemoveField(
            model_name='season',
            name='max_weeks',
        ),
        migrations.AddField(
            model_name='event',
            name='season',
            field=models.ForeignKey(blank=True, help_text='Season this event belongs to (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='sim.season'),
        ),
        migrations.AlterField(
            model_name='event',
            name='round_number',
            field=models.IntegerField(blank=True, help_text='Round number in series (was week_number in legacy model)', null=True),
        ),
    ]
