# Generated by Django 5.1.11 on 2025-06-19 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sim', '0003_alter_simulator_unique_together_simulator_icon_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='simprofile',
            old_name='is_active',
            new_name='is_verified',
        ),
        migrations.AlterField(
            model_name='simulator',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
