# Generated by Django 5.1.11 on 2025-06-19 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sim', '0004_rename_is_active_simprofile_is_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simprofile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
