# Generated by Django 5.1.11 on 2025-06-28 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sim', '0004_remove_season_current_race_week_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='allowed_licenses',
            field=models.JSONField(blank=True, help_text='Allowed license groups as returned by iRacing API (raw list).', null=True),
        ),
    ]
