# Generated by Django 5.1.11 on 2025-06-28 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sim', '0005_series_allowed_licenses'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo image downloaded from iRacing assets', null=True, upload_to='series/logos/'),
        ),
    ]
