# Generated by Django 5.1.11 on 2025-06-21 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sim', '0005_set_is_verified_default_false'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='event',
            name='sim_event_type_dc849f_idx',
        ),
        migrations.AlterUniqueTogether(
            name='carmodel',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='simlayout',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='simtrack',
            unique_together={('simulator', 'sim_api_id'), ('simulator', 'track_model')},
        ),
        migrations.AlterUniqueTogether(
            name='trackmodel',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='carclass',
            name='slug',
            field=models.SlugField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='slug',
            field=models.SlugField(blank=True, max_length=280),
        ),
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(blank=True, max_length=280),
        ),
        migrations.AddField(
            model_name='eventclass',
            name='slug',
            field=models.SlugField(blank=True, max_length=280),
        ),
        migrations.AddField(
            model_name='eventinstance',
            name='slug',
            field=models.SlugField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='series',
            name='slug',
            field=models.SlugField(blank=True, max_length=280),
        ),
        migrations.AddField(
            model_name='simlayout',
            name='slug',
            field=models.SlugField(blank=True, max_length=280),
        ),
        migrations.AddField(
            model_name='simtrack',
            name='slug',
            field=models.SlugField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='trackmodel',
            name='slug',
            field=models.SlugField(blank=True, max_length=280),
        ),
        migrations.AlterUniqueTogether(
            name='carmodel',
            unique_together={('manufacturer', 'name', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='eventclass',
            unique_together={('event', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='eventinstance',
            unique_together={('event', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='simlayout',
            unique_together={('sim_track', 'layout_code', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='simtrack',
            unique_together={('simulator', 'sim_api_id'), ('simulator', 'slug'), ('simulator', 'track_model')},
        ),
        migrations.AlterUniqueTogether(
            name='trackmodel',
            unique_together={('name', 'country', 'slug')},
        ),
        migrations.AddIndex(
            model_name='carmodel',
            index=models.Index(fields=['slug'], name='sim_carmode_slug_aa4fab_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['sim_layout'], name='sim_event_sim_lay_21fc33_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['event_date'], name='sim_event_event_d_64c9d1_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['slug'], name='sim_event_slug_5d6224_idx'),
        ),
        migrations.AddIndex(
            model_name='eventclass',
            index=models.Index(fields=['event', 'slug'], name='sim_eventcl_event_i_8c203c_idx'),
        ),
        migrations.AddIndex(
            model_name='eventinstance',
            index=models.Index(fields=['event', 'slug'], name='sim_eventin_event_i_7df41c_idx'),
        ),
        migrations.AddIndex(
            model_name='series',
            index=models.Index(fields=['slug'], name='sim_series_slug_3d94f6_idx'),
        ),
        migrations.AddIndex(
            model_name='simlayout',
            index=models.Index(fields=['sim_track', 'slug'], name='sim_simlayo_sim_tra_c63ed2_idx'),
        ),
        migrations.AddIndex(
            model_name='simtrack',
            index=models.Index(fields=['simulator'], name='sim_simtrac_simulat_5dec09_idx'),
        ),
        migrations.AddIndex(
            model_name='simtrack',
            index=models.Index(fields=['simulator', 'slug'], name='sim_simtrac_simulat_133955_idx'),
        ),
        migrations.AddIndex(
            model_name='trackmodel',
            index=models.Index(fields=['slug'], name='sim_trackmo_slug_f4115e_idx'),
        ),
    ]
