# Generated by Django 5.1.11 on 2025-07-02 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sim', '0006_series_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackmodel',
            name='site_url',
            field=models.URLField(blank=True, help_text='Official simulator site URL for this track (from track assets API)'),
        ),
    ]
