# Generated by Django 5.1.11 on 2025-07-02 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sim', '0007_trackmodel_site_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='allowed_car_class_ids',
        ),
        migrations.RemoveField(
            model_name='series',
            name='allowed_licenses',
        ),
        migrations.RemoveField(
            model_name='series',
            name='car_switching',
        ),
        migrations.RemoveField(
            model_name='series',
            name='fair_share_pct',
        ),
        migrations.RemoveField(
            model_name='series',
            name='incident_limit',
        ),
        migrations.RemoveField(
            model_name='series',
            name='is_team_event',
        ),
        migrations.RemoveField(
            model_name='series',
            name='max_drivers_per_entry',
        ),
        migrations.RemoveField(
            model_name='series',
            name='max_team_drivers',
        ),
        migrations.RemoveField(
            model_name='series',
            name='min_drivers_per_entry',
        ),
        migrations.RemoveField(
            model_name='series',
            name='region_competition',
        ),
    ]
