# Generated by Django 5.1.11 on 2025-06-23 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sim', '0007_add_unified_participation_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_source',
            field=models.CharField(choices=[('SPECIAL', 'Special Event - Official'), ('SERIES', 'Series Event - Official'), ('CLUB', 'Club-Organized Event'), ('USER', 'User-Created Event')], default='USER', help_text='Source/type of this event', max_length=20),
        ),
    ]
