# Generated by Django 5.1.11 on 2025-07-02 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sim', '0008_remove_series_allowed_car_class_ids_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='cross_license',
        ),
        migrations.RemoveField(
            model_name='series',
            name='fixed_setup',
        ),
        migrations.RemoveField(
            model_name='series',
            name='license_group',
        ),
        migrations.RemoveField(
            model_name='series',
            name='multiclass',
        ),
    ]
