# Generated by Django 5.1.11 on 2025-06-24 08:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sim', '0008_alter_event_event_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='simprofile',
            name='sim_simprof_user_id_c94dd1_idx',
        ),
        migrations.RemoveIndex(
            model_name='simprofile',
            name='sim_simprof_simulat_af3750_idx',
        ),
        migrations.AlterUniqueTogether(
            name='simprofile',
            unique_together={('simulator', 'external_data_id')},
        ),
        migrations.AddField(
            model_name='simprofile',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Whether this profile appears in public searches and listings'),
        ),
        migrations.AddField(
            model_name='simprofile',
            name='linked_at',
            field=models.DateTimeField(blank=True, help_text='When this profile was linked to the current user', null=True),
        ),
        migrations.AddField(
            model_name='simprofile',
            name='linked_user',
            field=models.ForeignKey(blank=True, help_text='User who has claimed this profile', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_sim_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='simprofile',
            name='profile_data',
            field=models.JSONField(default=dict, help_text='Platform-specific profile data (stats, achievements, etc.)'),
        ),
        migrations.AddField(
            model_name='simulator',
            name='slug',
            field=models.SlugField(blank=True, max_length=280, unique=True),
        ),
        migrations.AlterField(
            model_name='simprofile',
            name='external_data_id',
            field=models.CharField(blank=True, help_text='Platform-specific unique ID (e.g., iRacing customer ID)', max_length=255),
        ),
        migrations.AlterField(
            model_name='simprofile',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='True if the linked user has verified ownership of this profile'),
        ),
        migrations.AlterField(
            model_name='simprofile',
            name='preferences',
            field=models.JSONField(blank=True, help_text='User-controlled preferences and settings', null=True),
        ),
        migrations.AlterField(
            model_name='simprofile',
            name='profile_name',
            field=models.CharField(help_text='Display name on the platform', max_length=255),
        ),
        migrations.AddIndex(
            model_name='simprofile',
            index=models.Index(fields=['simulator', 'external_data_id'], name='sim_simprof_simulat_77d43c_idx'),
        ),
        migrations.AddIndex(
            model_name='simprofile',
            index=models.Index(fields=['linked_user'], name='sim_simprof_linked__c56419_idx'),
        ),
        migrations.AddIndex(
            model_name='simprofile',
            index=models.Index(fields=['is_public'], name='sim_simprof_is_publ_2961b9_idx'),
        ),
        migrations.AddIndex(
            model_name='simprofile',
            index=models.Index(fields=['profile_name'], name='sim_simprof_profile_b205fa_idx'),
        ),
        migrations.RemoveField(
            model_name='simprofile',
            name='user',
        ),
    ]
