# Generated by Django 5.1.11 on 2025-07-02 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sim', '0009_remove_series_cross_license_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='series',
            unique_together={('simulator', 'external_series_id')},
        ),
    ]
