# Generated by Django 5.1.11 on 2025-06-25 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sim', '0009_remove_simprofile_sim_simprof_user_id_c94dd1_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimProfileCarOwnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acquired_at', models.DateTimeField(auto_now_add=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('sim_car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='sim.simcar')),
                ('sim_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_cars', to='sim.simprofile')),
            ],
            options={
                'verbose_name': 'Car Ownership',
                'verbose_name_plural': 'Car Ownerships',
                'unique_together': {('sim_profile', 'sim_car')},
            },
        ),
        migrations.CreateModel(
            name='SimProfileTrackOwnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acquired_at', models.DateTimeField(auto_now_add=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('sim_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_tracks', to='sim.simprofile')),
                ('sim_track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='sim.simtrack')),
            ],
            options={
                'verbose_name': 'Track Ownership',
                'verbose_name_plural': 'Track Ownerships',
                'unique_together': {('sim_profile', 'sim_track')},
            },
        ),
    ]
