# Generated by Django 5.1.11 on 2025-06-26 00:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sim', '0010_simprofilecarownership_simprofiletrackownership'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='simcar',
            unique_together={('simulator', 'car_model'), ('simulator', 'sim_api_id')},
        ),
        migrations.AddField(
            model_name='carmodel',
            name='abbreviated_name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='ai_enabled',
            field=models.BooleanField(default=True, help_text='AI can drive this car'),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='car_types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, help_text='Array of car types for searching (cleaned from API car_types)', size=None),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='category',
            field=models.CharField(choices=[('formula_car', 'Formula Car'), ('oval', 'Oval'), ('sports_car', 'Sports Car')], default='sports_car', help_text='Primary car category from iRacing API', max_length=20),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='full_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='has_headlights',
            field=models.BooleanField(default=False, help_text='Whether car has headlights'),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='has_multiple_dry_tire_types',
            field=models.BooleanField(default=False, help_text='Multiple dry tire compounds available'),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='has_rain_capable_tire_types',
            field=models.BooleanField(default=False, help_text='Rain tires available'),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='horsepower',
            field=models.IntegerField(blank=True, help_text='HP from iRacing API', null=True),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='rain_enabled',
            field=models.BooleanField(default=False, help_text='Can race in rain conditions'),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='search_filters',
            field=models.CharField(blank=True, help_text='Search filters from iRacing API for advanced searching', max_length=500),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='weight_lbs',
            field=models.IntegerField(blank=True, help_text='Car weight in pounds', null=True),
        ),
        migrations.AddField(
            model_name='simcar',
            name='display_name',
            field=models.CharField(blank=True, help_text='Full display name from car_name field', max_length=255),
        ),
        migrations.AddField(
            model_name='simcar',
            name='free_with_subscription',
            field=models.BooleanField(default=False, help_text='Free with base subscription'),
        ),
        migrations.AddField(
            model_name='simcar',
            name='is_purchasable',
            field=models.BooleanField(default=True, help_text='Can be purchased (is_ps_purchasable)'),
        ),
        migrations.AddField(
            model_name='simcar',
            name='large_image',
            field=models.ImageField(blank=True, help_text='Main/hero image', null=True, upload_to='cars/images/'),
        ),
        migrations.AddField(
            model_name='simcar',
            name='logo',
            field=models.ImageField(blank=True, help_text='Car/manufacturer logo', null=True, upload_to='cars/logos/'),
        ),
        migrations.AddField(
            model_name='simcar',
            name='max_power_adjust_pct',
            field=models.IntegerField(default=0, help_text='Maximum power adjustment percentage'),
        ),
        migrations.AddField(
            model_name='simcar',
            name='max_weight_penalty_kg',
            field=models.IntegerField(default=0, help_text='Maximum weight penalty in kg'),
        ),
        migrations.AddField(
            model_name='simcar',
            name='min_power_adjust_pct',
            field=models.IntegerField(default=0, help_text='Minimum power adjustment percentage'),
        ),
        migrations.AddField(
            model_name='simcar',
            name='package_id',
            field=models.IntegerField(default=0, help_text='package_id from iRacing API for ownership tracking'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='simcar',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price in USD', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='simcar',
            name='price_display',
            field=models.CharField(blank=True, help_text='Formatted price string', max_length=50),
        ),
        migrations.AddField(
            model_name='simcar',
            name='small_image',
            field=models.ImageField(blank=True, help_text='Thumbnail image', null=True, upload_to='cars/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='simcar',
            name='sim_api_id',
            field=models.CharField(help_text='car_id from iRacing API for API calls', max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='simcar',
            unique_together={('simulator', 'car_model'), ('simulator', 'package_id'), ('simulator', 'sim_api_id')},
        ),
        migrations.AddIndex(
            model_name='carmodel',
            index=models.Index(fields=['manufacturer'], name='sim_carmode_manufac_73f933_idx'),
        ),
        migrations.AddIndex(
            model_name='carmodel',
            index=models.Index(fields=['category'], name='sim_carmode_categor_dbabb8_idx'),
        ),
        migrations.AddIndex(
            model_name='carmodel',
            index=models.Index(fields=['full_name'], name='sim_carmode_full_na_969acf_idx'),
        ),
        migrations.AddIndex(
            model_name='carmodel',
            index=models.Index(fields=['horsepower'], name='sim_carmode_horsepo_7788b2_idx'),
        ),
        migrations.AddIndex(
            model_name='carmodel',
            index=models.Index(fields=['weight_lbs'], name='sim_carmode_weight__506eb8_idx'),
        ),
        migrations.AddIndex(
            model_name='carmodel',
            index=models.Index(fields=['rain_enabled'], name='sim_carmode_rain_en_c6705e_idx'),
        ),
        migrations.AddIndex(
            model_name='carmodel',
            index=models.Index(fields=['has_headlights'], name='sim_carmode_has_hea_128e22_idx'),
        ),
        migrations.AddIndex(
            model_name='carmodel',
            index=models.Index(fields=['car_types'], name='car_model_types_gin'),
        ),
        migrations.AddIndex(
            model_name='simcar',
            index=models.Index(fields=['simulator', 'sim_api_id'], name='sim_simcar_simulat_3f508c_idx'),
        ),
        migrations.AddIndex(
            model_name='simcar',
            index=models.Index(fields=['simulator', 'package_id'], name='sim_simcar_simulat_6b6231_idx'),
        ),
        migrations.AddIndex(
            model_name='simcar',
            index=models.Index(fields=['package_id'], name='sim_simcar_package_657439_idx'),
        ),
        migrations.AddIndex(
            model_name='simcar',
            index=models.Index(fields=['is_active'], name='sim_simcar_is_acti_e8cada_idx'),
        ),
        migrations.AddIndex(
            model_name='simcar',
            index=models.Index(fields=['free_with_subscription'], name='sim_simcar_free_wi_53c096_idx'),
        ),
        migrations.AddIndex(
            model_name='simcar',
            index=models.Index(fields=['is_purchasable'], name='sim_simcar_is_purc_14387c_idx'),
        ),
        migrations.AddIndex(
            model_name='simcar',
            index=models.Index(fields=['price'], name='sim_simcar_price_3b6622_idx'),
        ),
    ]
