# Generated by Django 5.1.11 on 2025-07-02 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sim', '0010_alter_series_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='season',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
