# Generated by Django 5.1.11 on 2025-07-03 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sim', '0011_alter_season_end_date_alter_season_start_date'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='event',
            name='sim_event_event_d_64c9d1_idx',
        ),
        migrations.RemoveField(
            model_name='event',
            name='entry_requirements',
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='weather',
        ),
        migrations.AddField(
            model_name='event',
            name='additional_details',
            field=models.JSONField(blank=True, help_text='Additional details like specific licenses, achievements, etc.', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='multiclass',
            field=models.BooleanField(default=False),
        ),
    ]
