# Generated by Django 5.1.11 on 2025-06-26 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sim', '0011_add_car_data_fields'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='simcar',
            unique_together={('simulator', 'package_id'), ('simulator', 'sim_api_id')},
        ),
    ]
