# Generated by Django 5.1.11 on 2025-06-26 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sim', '0012_remove_car_model_unique_constraint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simcar',
            name='image_url',
        ),
    ]
