# Generated by Django 5.1.11 on 2025-07-03 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sim', '0012_remove_event_sim_event_event_d_64c9d1_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsession',
            name='laps',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_source',
            field=models.CharField(choices=[('OFFICIAL', 'Official Simulator Event'), ('CLUB', 'Club-Organized Event'), ('USER', 'User-Created Event')], default='USER', help_text='Source/type of this event', max_length=20),
        ),
        migrations.AlterField(
            model_name='eventsession',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
