# Generated by Django 5.1.11 on 2025-07-03 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sim', '0013_eventsession_laps_alter_event_event_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='simulated_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
