# Generated by Django 5.1.11 on 2025-06-26 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sim', '0013_remove_image_url_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simtrack',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='trackmodel',
            name='default_image_url',
        ),
        migrations.AddField(
            model_name='simlayout',
            name='allow_rolling_start',
            field=models.BooleanField(default=True, help_text='Whether rolling starts are allowed'),
        ),
        migrations.AddField(
            model_name='simlayout',
            name='corners_per_lap',
            field=models.IntegerField(blank=True, help_text='Number of corners per lap', null=True),
        ),
        migrations.AddField(
            model_name='simlayout',
            name='fully_lit',
            field=models.BooleanField(default=False, help_text='Track is fully lit for night racing'),
        ),
        migrations.AddField(
            model_name='simlayout',
            name='grid_stalls',
            field=models.IntegerField(blank=True, help_text='Number of grid starting positions', null=True),
        ),
        migrations.AddField(
            model_name='simlayout',
            name='layout_type',
            field=models.CharField(choices=[('ROAD', 'Road'), ('OVAL', 'Oval'), ('STREET', 'Street'), ('RALLY', 'Rally'), ('DRAG', 'Drag'), ('DIRT_ROAD', 'Dirt Road'), ('DIRT_OVAL', 'Dirt Oval'), ('OTHER', 'Other')], default='ROAD', help_text='Specific layout type (road, oval, dirt_road, dirt_oval, etc.)', max_length=20),
        ),
        migrations.AddField(
            model_name='simlayout',
            name='max_cars',
            field=models.IntegerField(blank=True, help_text='Maximum cars supported on this layout', null=True),
        ),
        migrations.AddField(
            model_name='simlayout',
            name='night_lighting',
            field=models.BooleanField(default=False, help_text='Track has night lighting capabilities'),
        ),
        migrations.AddField(
            model_name='simlayout',
            name='number_pitstalls',
            field=models.IntegerField(blank=True, help_text='Number of pit stalls available', null=True),
        ),
        migrations.AddField(
            model_name='simlayout',
            name='pit_road_speed_limit',
            field=models.IntegerField(blank=True, help_text='Pit road speed limit (mph/kph)', null=True),
        ),
        migrations.AddField(
            model_name='simlayout',
            name='qualify_laps',
            field=models.IntegerField(blank=True, help_text='Number of qualifying laps', null=True),
        ),
        migrations.AddField(
            model_name='simlayout',
            name='retired',
            field=models.BooleanField(default=False, help_text='Layout is retired/deprecated'),
        ),
        migrations.AddField(
            model_name='simtrack',
            name='is_free',
            field=models.BooleanField(default=False, help_text='Free with subscription'),
        ),
        migrations.AddField(
            model_name='simtrack',
            name='is_purchasable',
            field=models.BooleanField(default=True, help_text='Can be purchased'),
        ),
        migrations.AddField(
            model_name='simtrack',
            name='large_image',
            field=models.ImageField(blank=True, help_text='Main/hero image', null=True, upload_to='tracks/images/'),
        ),
        migrations.AddField(
            model_name='simtrack',
            name='logo',
            field=models.ImageField(blank=True, help_text='Track logo', null=True, upload_to='tracks/logos/'),
        ),
        migrations.AddField(
            model_name='simtrack',
            name='package_id',
            field=models.CharField(blank=True, help_text='Package ID from API for ownership tracking', max_length=50),
        ),
        migrations.AddField(
            model_name='simtrack',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Track price in USD', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='simtrack',
            name='rain_enabled',
            field=models.BooleanField(default=False, help_text='Rain weather supported'),
        ),
        migrations.AddField(
            model_name='simtrack',
            name='search_filters',
            field=models.CharField(blank=True, help_text='Search filters from API for optimization', max_length=500),
        ),
        migrations.AddField(
            model_name='simtrack',
            name='small_image',
            field=models.ImageField(blank=True, help_text='Thumbnail image', null=True, upload_to='tracks/thumbnails/'),
        ),
        migrations.AddField(
            model_name='trackmodel',
            name='category',
            field=models.CharField(blank=True, help_text="Track category: 'road' or 'oval'", max_length=20),
        ),
        migrations.AddField(
            model_name='trackmodel',
            name='time_zone',
            field=models.CharField(blank=True, help_text="Track time zone (e.g., 'America/New_York')", max_length=50),
        ),
        migrations.AlterField(
            model_name='simlayout',
            name='length_km',
            field=models.FloatField(help_text='Track configuration length in kilometers'),
        ),
        migrations.AlterField(
            model_name='simlayout',
            name='type',
            field=models.CharField(choices=[('ROAD', 'Road'), ('OVAL', 'Oval'), ('STREET', 'Street'), ('RALLY', 'Rally'), ('DRAG', 'Drag'), ('DIRT_ROAD', 'Dirt Road'), ('DIRT_OVAL', 'Dirt Oval'), ('OTHER', 'Other')], max_length=20),
        ),
    ]
