# Generated by Django 5.1.11 on 2025-07-04 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sim', '0014_event_simulated_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherforecast',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weather_forecasts', to='sim.event'),
        ),
        migrations.AlterField(
            model_name='weatherforecast',
            name='time_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weather_forecasts', to='sim.timeslot'),
        ),
    ]
