# Generated by Django 5.1.11 on 2025-06-26 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sim', '0014_add_comprehensive_track_fields'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='simcar',
            unique_together={('simulator', 'sim_api_id')},
        ),
    ]
