# Generated by Django 5.1.11 on 2025-07-05 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sim', '0015_weatherforecast_event_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='registration_deadline',
        ),
        migrations.AddField(
            model_name='event',
            name='registration_open_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
