# Generated by Django 5.1.11 on 2025-06-26 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sim', '0016_carrestriction_raceweek_season_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='simulator',
            field=models.ForeignKey(blank=True, help_text='Simulator this series belongs to (if simulator-specific)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='series', to='sim.simulator'),
        ),
        migrations.AddIndex(
            model_name='series',
            index=models.Index(fields=['simulator'], name='sim_series_simulat_53c06f_idx'),
        ),
    ]
