# Generated by Django 5.1.11 on 2025-06-26 19:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sim', '0018_eventresult_teamresult_participantresult_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='simprofile',
            name='sim_simprof_simulat_77d43c_idx',
        ),
        migrations.RenameField(
            model_name='simprofile',
            old_name='external_data_id',
            new_name='sim_api_id',
        ),
        migrations.AlterUniqueTogether(
            name='simprofile',
            unique_together={('simulator', 'sim_api_id')},
        ),
        migrations.AddIndex(
            model_name='simprofile',
            index=models.Index(fields=['simulator', 'sim_api_id'], name='sim_simprof_simulat_07fd75_idx'),
        ),
    ]
