# Generated by Django 5.1.11 on 2025-06-27 22:37

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sim', '0019_remove_simprofile_sim_simprof_simulat_77d43c_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carclass',
            name='rain_enabled',
            field=models.BooleanField(default=False, help_text='Whether rain is supported for this car class'),
        ),
        migrations.AddField(
            model_name='carclass',
            name='relative_speed',
            field=models.IntegerField(blank=True, help_text='Relative speed rating from simulator API', null=True),
        ),
        migrations.AddField(
            model_name='carclass',
            name='short_name',
            field=models.CharField(blank=True, help_text="Short display name (e.g., 'GT3 Class')", max_length=50),
        ),
        migrations.AddField(
            model_name='carclass',
            name='sim_api_id',
            field=models.CharField(blank=True, help_text='Car class ID from simulator API (e.g., car_class_id from iRacing)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='carclass',
            name='simulator',
            field=models.ForeignKey(blank=True, help_text='Simulator this car class belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car_classes', to='sim.simulator'),
        ),
        migrations.AddField(
            model_name='carrestriction',
            name='is_fixed_setup',
            field=models.BooleanField(default=False, help_text='Whether this car uses fixed setup'),
        ),
        migrations.AddField(
            model_name='event',
            name='allowed_car_class_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, help_text='Array of car class sim_api_ids allowed in this event (overrides series if set)', size=None),
        ),
        migrations.AddField(
            model_name='series',
            name='allowed_car_class_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, help_text='Array of car class sim_api_ids allowed in this series (from car_class_ids API field)', size=None),
        ),
        migrations.AlterField(
            model_name='carclass',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='carrestriction',
            name='power_adjust_pct',
            field=models.FloatField(default=0.0, help_text='Power adjustment percentage (can be decimal)'),
        ),
        migrations.AddIndex(
            model_name='carclass',
            index=models.Index(fields=['simulator'], name='sim_carclas_simulat_571f2e_idx'),
        ),
        migrations.AddIndex(
            model_name='carclass',
            index=models.Index(fields=['sim_api_id'], name='sim_carclas_sim_api_7fb0ee_idx'),
        ),
        migrations.AddIndex(
            model_name='carclass',
            index=models.Index(fields=['name'], name='sim_carclas_name_fa176e_idx'),
        ),
        migrations.AddIndex(
            model_name='carclass',
            index=models.Index(fields=['slug'], name='sim_carclas_slug_eb2e71_idx'),
        ),
        migrations.AddConstraint(
            model_name='carclass',
            constraint=models.UniqueConstraint(condition=models.Q(('sim_api_id__isnull', False), ('simulator__isnull', False)), fields=('simulator', 'sim_api_id'), name='unique_simulator_sim_api_id'),
        ),
    ]
