# Generated by Django 5.1.11 on 2025-06-27 22:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sim', '0020_enhance_car_class_restrictions_v2'),
    ]

    operations = [
        migrations.AddField(
            model_name='carclass',
            name='car_sim_api_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, help_text='Array of car sim_api_ids in this class (from cars_in_class API field)', size=None),
        ),
    ]
