# Generated by Django 5.1.11 on 2025-06-27 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sim', '0021_add_car_sim_api_ids_to_carclass'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='carmodel',
            name='sim_carmode_car_cla_dd31ae_idx',
        ),
        migrations.RemoveField(
            model_name='carmodel',
            name='car_class',
        ),
    ]
