# Generated by Django 5.1.11 on 2025-06-28 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sim', '0022_remove_carmodel_car_class_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventclass',
            name='class_order',
            field=models.IntegerField(default=0, help_text='Order for multi-class display (0=fastest class)'),
        ),
        migrations.AddField(
            model_name='eventclass',
            name='entry_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Entry fee for this class', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='eventclass',
            name='inherit_series_restrictions',
            field=models.BooleanField(default=True, help_text='Whether to inherit BOP from series/race week'),
        ),
        migrations.AddField(
            model_name='eventclass',
            name='max_entries',
            field=models.IntegerField(blank=True, help_text='Maximum entries allowed for this class', null=True),
        ),
        migrations.AddField(
            model_name='eventclass',
            name='min_entries',
            field=models.IntegerField(blank=True, help_text='Minimum entries needed for this class', null=True),
        ),
        migrations.AddIndex(
            model_name='eventclass',
            index=models.Index(fields=['class_order'], name='sim_eventcl_class_o_9e2123_idx'),
        ),
    ]
