# Generated by Django 5.1.11 on 2025-06-28 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sim', '0023_add_eventclass_multiclass_fields'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='eventclass',
            name='sim_eventcl_event_i_8c203c_idx',
        ),
        migrations.RemoveField(
            model_name='eventclass',
            name='allowed_sim_car_ids',
        ),
        migrations.AlterField(
            model_name='eventclass',
            name='inherit_series_restrictions',
            field=models.BooleanField(default=True, help_text='Whether to inherit BOP restrictions from series/race week'),
        ),
    ]
