# Generated by Django 5.1.11 on 2025-06-28 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sim', '0024_remove_eventclass_allowed_sim_car_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='raceweek',
            name='max_air_temp',
            field=models.FloatField(blank=True, help_text='Maximum forecasted air temp (Celsius)', null=True),
        ),
        migrations.AddField(
            model_name='raceweek',
            name='max_precip_chance',
            field=models.IntegerField(blank=True, help_text='Maximum precipitation chance percentage (0-100)', null=True),
        ),
        migrations.AddField(
            model_name='raceweek',
            name='min_air_temp',
            field=models.FloatField(blank=True, help_text='Minimum forecasted air temp (Celsius)', null=True),
        ),
    ]
