# Generated by Django 5.1.11 on 2025-06-28 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sim', '0021_add_event_raceweek_fk'),
        ('sim', '0025_raceweek_max_air_temp_raceweek_max_precip_chance_and_more'),
    ]

    operations = [
    ]
