# Generated by Django 5.1.11 on 2025-07-01 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='Profile image for the user account', null=True, upload_to='user_profiles/'),
        ),
    ]
