# Generated by Django 5.1.11 on 2025-07-04 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='timezone',
            field=models.CharField(choices=[('UTC', 'UTC'), ('US/Eastern', 'US - Eastern'), ('US/Central', 'US - Central'), ('US/Mountain', 'US - Mountain'), ('US/Pacific', 'US - Pacific'), ('Europe/London', 'Europe - London'), ('Europe/Paris', 'Europe - Paris'), ('Europe/Berlin', 'Europe - Berlin'), ('Europe/Rome', 'Europe - Rome'), ('Europe/Madrid', 'Europe - Madrid'), ('Asia/Tokyo', 'Asia - Tokyo'), ('Asia/Shanghai', 'Asia - Shanghai'), ('Asia/Kolkata', 'Asia - Kolkata'), ('Asia/Dubai', 'Asia - Dubai'), ('Australia/Sydney', 'Australia - Sydney'), ('Australia/Melbourne', 'Australia - Melbourne'), ('America/New_York', 'America - New York'), ('America/Chicago', 'America - Chicago'), ('America/Denver', 'America - Denver'), ('America/Los_Angeles', 'America - Los Angeles'), ('America/Toronto', 'America - Toronto'), ('America/Vancouver', 'America - Vancouver'), ('America/Mexico_City', 'America - Mexico City'), ('America/Sao_Paulo', 'America - Sao Paulo'), ('Africa/Cairo', 'Africa - Cairo'), ('Africa/Johannesburg', 'Africa - Johannesburg')], default='UTC', help_text='Your preferred timezone for displaying dates and times', max_length=50, verbose_name='Timezone'),
        ),
    ]
